### ISSUE TITLE
Feedback op README (van Mediahuis)

### ISSUE THREAD

**Issue by julia-stevens** [kimnikitaschijf/look-and-feel-styleguide#1]
# Feedback op README
* In de README staat een duidelijk overzicht van de styleguide
* Er staan ook duidelijk afspraken over hoe jullie de stylesheet gaan aanpassen en over de naamgeving. 

* Het is alleen nog niet duidelijk hoe je dit zou moeten gebruiken, bijvoorbeeld welke class moet ik in HTML zetten om een bepaalde kleur te krijgen? 

@vsheo
@poormoa00

**Comment by ambersr** [comment]
Thanks! We hebben dit aangepast. 

Commit: 32e9ad0e312275dda346551c3b1fd6b095f22c8a
