### ISSUE TITLE
waarom gebruik je !important

### ISSUE THREAD

**Issue by Yu-Jing-van-Gerwen** [kimnikitaschijf/look-and-feel-styleguide#10]
als je alleen van plan bent om een hover te gebruiken kan je important weghalen

`A ! delimiter followed by the important keyword marks the declaration as important. The !important flag alters the rules selecting declarations inside the [cascade](https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade). A declaration that is not important is called normal.`

https://github.com/kimnikitaschijf/look-and-feel-styleguide/blob/8dabde984d492de056ee90ecc3d3122811efcce2/biebinbloei.css#L405-L407

hier lees je meer over important
https://developer.mozilla.org/en-US/docs/Web/CSS/important

**Comment by kimnikitaschijf** [comment]
Is geprobeerd, maar werkt helaas niet. Moet er dus in blijven staan.
