### ISSUE TITLE
Link werkt niet

### ISSUE THREAD

**Issue by KrijnHoetmer** [kimnikitaschijf/look-and-feel-styleguide#16]
De link naar jullie gedeelde stylesheet werkt niet. Gebruik hiervoor https://kimnikitaschijf.github.io/look-and-feel-styleguide/biebinbloei.css, zodat andere developers deze ook kunnen gebruiken in hun code.

https://github.com/kimnikitaschijf/look-and-feel-styleguide/blob/960096b8e1615d0243493cacecc87e8e414066fe/index.html#L20-L21

**Comment by ambersr** [comment]
Commit: 9c273a5da6550303bbb5d02c9b941cb8bdfe6b60
