### ISSUE TITLE
Classes gebruiken

### ISSUE THREAD

**Issue by KoopReynders** [kimnikitaschijf/look-and-feel-styleguide#17]
https://github.com/kimnikitaschijf/look-and-feel-styleguide/blob/d44921cddab9c2f5c9eecd2128892f69423f9191/biebinbloei.css#L130-L171

In de styleguide stylesheet kan je beter `classes` gebruiken en geen element selectors. Daarmee kan je de styleghuidek 'makkelijker' toepassen en kan je in je eigen styles de element selectors gebruiken.

**Comment by kimnikitaschijf** [comment]
Wij hebben classes toegevoegd voor de tekst. Dit is te zien in commit:

https://github.com/kimnikitaschijf/look-and-feel-styleguide/commit/17312d8245afbf19c6e8329402b35369f03f60a1
