### ISSUE TITLE
Feedback indeling van stylesheet (van Mediahuis)

### ISSUE THREAD

**Issue by julia-stevens** [kimnikitaschijf/look-and-feel-styleguide#2]
## Feedback indeling van stylesheet (van Mediahuis)

Wij vonden de indeling van de stylesheet niet helemaal overzichtelijk. Dit komt omdat er verschillende soorten elementen door elkaar staan, zie bijvoorbeeld hier: 

https://github.com/kimnikitaschijf/look-and-feel-styleguide/blob/8dabde984d492de056ee90ecc3d3122811efcce2/biebinbloei.css#L37-L161

Hier staan eerst de `@font-face`, `heading`, dan een stuk over kleuren en dan weer `h1-h6`. Misschien kunnen jullie deze verschillende elementen meer bij elkaar zetten? 

@vsheo
@poormoa00

**Comment by kimnikitaschijf** [comment]
Hebben hiernaar gekeken en hebben de layout op een logische volgorde gezet. 

[https://github.com/kimnikitaschijf/look-and-feel-styleguide/commit/1a7cedcadf8fe3ac86bde5a61fae73bcef60d38c](url)
