### ISSUE TITLE
Feedback Naamgeving (van Mediahuis)

### ISSUE THREAD

**Issue by julia-stevens** [kimnikitaschijf/look-and-feel-styleguide#3]
## Feedback Naamgeving

https://github.com/kimnikitaschijf/look-and-feel-styleguide/blob/8dabde984d492de056ee90ecc3d3122811efcce2/biebinbloei.css#L8-L12
In het geval dat jullie in de toekomst de kleuren gaan veranderen, dan klopt de naamgeving van een aantal properties niet meer, en zou je dus veel extra werk hebben, zoals hier: 

https://github.com/kimnikitaschijf/look-and-feel-styleguide/blob/8dabde984d492de056ee90ecc3d3122811efcce2/biebinbloei.css#L88-L90
Hier gebruiken jullie weer hex-codes, terwijl de kleur al is gedefinieerd in de body met `--lightgreen`. Je zou dit dus kunnen aanpassen naar onderstaand. Hiermee zorg je ervoor dat je maar één keer de kleur hoeft aan te passen, als deze verandert. 

```css
.color1 {
background-color: var(--lightgreen);
}
```

Jullie gebruiken hier ook de naam 'color1', misschien zou je hier een meer beschrijvende naam kunnen gebruiken, van waarvoor deze class gebruikt kan worden (background, primary, etc...)?

@vsheo
@poormoa00

**Comment by kimnikitaschijf** [comment]
Is aangepast. Hebben dit over het hoofd gezien 👍 

[https://github.com/kimnikitaschijf/look-and-feel-styleguide/commit/81ab70f9d6f2cfe570db07837b564aac4725570c](url)
