### ISSUE TITLE
Feedback Volledigheid Stylesheet (van Mediahuis)

### ISSUE THREAD

**Issue by julia-stevens** [kimnikitaschijf/look-and-feel-styleguide#4]
## Feedback Volledigheid Stylesheet

Wij vinden dat het er erg volledig uit ziet!

Mocht het voor jullie nog van toepassing zijn, dan zouden jullie nog naar foutmeldingen kunnen kijken bij formulieren. 

@vsheo
@poormoa00

**Comment by ambersr** [comment]
Commit: fdb642b9a008697592a8a632944755b2efd89cf7
