### ISSUE TITLE
Feedback Customer properties op juiste element (van Mediahuis)

### ISSUE THREAD

**Issue by julia-stevens** [kimnikitaschijf/look-and-feel-styleguide#5]
## Feedback Customer properties op juiste element (van Mediahuis)

Jullie hebben in de `body` custom properties gedefinieerd, maar maken hier niet overal gebruik van. Dit komt vooral terug bij de kleuren: https://github.com/kimnikitaschijf/look-and-feel-styleguide/blob/8dabde984d492de056ee90ecc3d3122811efcce2/biebinbloei.css#L88-L119

Zie #3 voor onze suggestie

@vsheo
@poormoa00

**Comment by kimnikitaschijf** [comment]
Is aangepast. Zie 'comment' van #3 voor bewijslast.
