### ISSUE TITLE
Feedback Herhaling (van Mediahuis)

### ISSUE THREAD

**Issue by julia-stevens** [kimnikitaschijf/look-and-feel-styleguide#6]
## Feedback Herhaling (van Mediahuis)

Een aantal onderdelen komen vaak voor en zouden jullie misschien om kunnen zetten naar een custom property en deze met een var() aanroepen: 
* `line-height`
* `align-items`
* `font-size: clamp()`

@vsheo
@poormoa00

**Comment by ambersr** [comment]
Alle font-sizes hebben een verschillende clamp en line-height. Dit wordt anders te ingewikkeld als we deze als variabele gaan gebruiken. 

Commit naar aangepaste code: de3c409116031f292c881f5de1e3dc25a88f4740
