### ISSUE TITLE
acessibility radio options

### ISSUE THREAD

**Issue by dpfqvpwtyk** [kimnikitaschijf/look-and-feel-styleguide#8]
als je door de website heen gaat met de tab knop slaat hij de opties van de radio options over

@keremttc @Ravirkt @nadiachaja

**Comment by ambersr** [comment]
Ik heb hier research naar gedaan. Binnen de radiobutton options maak je gebruik van de pijltjes omdat er maar 1 optie mogelijk is om te kiezen. Bij een checkbox kan je wel tussen de opties kiezen met de tab functie. Dit is omdat er meerdere opties mogelijk zijn. 

Als ik dit ga aanpassen in de code is het voor gebruikers met een screenreader niet meer logisch omdat ze normaal gesproken de radiobutton opties met de pijltjes navigeren en niet met de tab toets. Om deze reden ga ik de code niet aanpassen.

Linkje naar bron van research: https://accessibleweb.com/question-answer/how-should-keyboard-navigation-work-in-a-group-of-radio-buttons/
