### ISSUE TITLE
Herhaling van code

### ISSUE THREAD

**Issue by dpfqvpwtyk** [kimnikitaschijf/look-and-feel-styleguide#9]
In de css van de stylesheet is nogal wat herhaling. Zo staat er bijvoorbeeld bij H1 t/m H6 apart dat het dezelfde font moet hebben.

@keremttc @Ravirkt @nadiachaja

**Comment by ambersr** [comment]
Opgelost zie commit!

2cc548caf810f0a34b66294d460a71269efe68d3

**Comment by ambersr** [comment]
Opgelost zie commit!

2cc548caf810f0a34b66294d460a71269efe68d3
